sudo: required

dist: trusty
  
language: php
  
services:
  - mysql

cache:
  directories:
    - $HOME/.npm
    
addons:
  apt:
    packages:
      - php5-fpm
      - php5-mysql
    
before_install:
  - npm install tape
  - npm install chrome-launcher
  - npm install chrome-remote-interface
  # create the databases that will be used by the site using `mysql` binary
  # user is `root`, password is empty and host is `localhost`
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
 
node_js:
    - "node"
    
env:
  global:
    - SITE_URL="http://site.localhost"
    - SITE_DOMAIN="site.localhost"
    - DB_NAME="test"
   
matrix:
  fast_finish: true
    
branches:
  only:
    - master

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  
  - sudo service php5-fpm restart
  
  
  #- mysql -u root -e "CREATE USER 'myproject'@'localhost' IDENTIFIED BY 'mypass'"
  #- mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'myproject'@'localhost' WITH GRANT OPTION;"
    #- bin/vendors install
    #- app/console doctrine:database:create
    #- app/console doctrine:schema:update --force
    #- app/console doctrine:fixtures:load
  
script:
  - node index.js
#- curl http://127.0.0.1/test.php
#- curl http://localhost/test.php
#- curl http://localhost/test.php?tttt=6666
#- curl http://localhost/test.php?tttt=ccccc
